name: Ubuntu
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - master

env:
  SCHEME: scheme
  IDRIS2_TESTS_CG: chez

jobs:
  build:
    runs-on: ubuntu-latest
    container: snazzybucket/idris2:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: idris build and test
        run: |
          make clean && make build && make install && make test INTERACTIVE=''
        shell: bash
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build docker image
        run: |
          make clean
          make docker-build
        shell: bash
      - name: test docker image
        run: |
          make docker-run
        shell: bash
  generate-docs:
    needs: [build, build-docker]
    runs-on: ubuntu-latest
    container: snazzybucket/idris2:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: generate docs
        run: |
          make docs
        shell: bash
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: docs
          path: build/docs
  deploy-docs:
    needs: [generate-docs]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: docs
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: 'docs'
